services:
  - type: web
    name: xca-backend
    runtime: python
    rootDir: xca-backend/backend
    buildCommand: pip install -r ../../requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"